version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: ["npm", "run", "start:dev"]
