apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iso-ingress
spec:
  rules:
  - host: <your-domain>
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: iso-svc
            port:
              number: 80
