apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iso-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  rules:
  - host: ad6e23119e5764ff384b4b37156954da-df90059a4a9ee9e1.elb.eu-west-1.amazonaws.com
    http:
      paths:
      - path: /ita
        backend:
          serviceName: iso-svc-ita
          port:
            number: 80
      - path: /eng
        backend:
          serviceName: iso-svc
          port:
            number: 80
