## write a deployment spec for the isolates service

apiVersion: apps/v1
kind: Deployment
metadata:
  name: isolates
  labels:
    app: isolates
spec:
  replicas: 3
  selector:
    matchLabels:
      app: isolates
  template:
    metadata:
      labels:
        app: isolates
    spec:
      containers:
      - name: isolates
        image: 317884193661.dkr.ecr.eu-west-1.amazonaws.com/isolates:b69724b19daa6f428ad958c0da91428bad5b89c0
        imagePullPolicy: Always
        ports:
        - containerPort: 80