## write a deployment spec for the isolates service

apiVersion: apps/v1
kind: Deployment
metadata:
  name: isolates
  labels:
    app: isolates
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # The maximum number of pods that can be created above the desired number of pods
      maxUnavailable: 1 # The maximum number of pods that can be unavailable during the update
  selector:
    matchLabels:
      app: isolates
  template:
    metadata:
      labels:
        app: isolates
    spec:
      containers:
      - name: isolates
        image: 317884193661.dkr.ecr.eu-west-1.amazonaws.com/isolates:7e416621153887ae6c272f8aaf35cbb34afb4615
        imagePullPolicy: Always
        ports:
        - containerPort: 80