name: Deploy to ECR and update Argo CI manifest

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      # Get the SHA of the commit
      - name: Get commit SHA
        id: commit_sha
        run: echo "::set-output name=sha::$(echo ${GITHUB_SHA})"

      # Login to ECR
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      # Build the Docker image
      - name: Build the image
        run: |
          docker-compose build -t ${{ secrets.ECR_REGISTRY }}/isolates:${{ steps.commit_sha.outputs.sha }} .

      # Push the image to ECR
      - name: Push the image to ECR
        run: |
          docker push ${{ secrets.ECR_REGISTRY }}/isolates:${{ steps.commit_sha.outputs.sha }}

      # Clone the repository containing the Argo CI manifest
      - name: Clone the manifest repository
        uses: actions/checkout@v2
        with:
          repository: kofikodie/local-manifest
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      # Update the Argo CI manifest
      - name: Update the Argo CI manifest
        run: |
          cd charts
          sed -i "s|image: .*|image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/my-image:${{ steps.commit_sha.outputs.sha }}|" iso-ds.yaml
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add iso-ds.yaml
          git commit -m "Update Argo CI manifest"

      # Push the updated manifest to the repository
      - name: Push the updated manifest
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
